----------------------------------------------------------------------
-- DDL for PostgreSQL
--   generated by kwatable with template 'ddl-postgresql.eruby'
--   at Sun Sep 17 21:18:58 JST 2006
----------------------------------------------------------------------

-- group master table
drop table groups;
create table groups (
   id                   serial               primary key,
   name                 varchar(63)          not null unique,
   "desc"               text                 
);

-- member master table
drop table members;
create table members (
   id                   serial               primary key,
   name                 varchar(63)          not null unique,
   "desc"               text                 ,
   email                varchar(63)          ,
   gender               varchar(1)           ,  -- M,W,X
   birth                date                 ,
   group_id             integer              not null references groups(id),
   created_at           timestamp            not null,
   updated_at           timestamp            not null
);
