----------------------------------------------------------------------
-- DDL for PostgreSQL
--   generated by kwatable with template 'ddl-postgresql.eruby'
--   at Mon Aug 07 07:12:56 JST 2006
----------------------------------------------------------------------

-- group master table
create table groups (
   id                   serial               primary key,
   name                 varchar(63)          not null unique,
   "desc"               text                 
);

-- member master table
create table members (
   id                   serial               primary key,
   name                 varchar(63)          not null unique,
   "desc"               text                 ,
   email                varchar(63)          ,
   gender               varchar(1)           ,  -- M,W,X
   birth                date                 ,
   group_id             integer              not null references groups(id),
   created_at           timestamp            not null,
   modified_at          timestamp            not null
);
