
all:
	cd border1;	$(MAKE)
	cd border2;	$(MAKE)
	cd border3;	$(MAKE)
	cd breadcrumbs;	$(MAKE)
	cd calendar;	$(MAKE)
	cd form1;	$(MAKE)
	cd thumbnail;	$(MAKE)
	cd pagelayout;	$(MAKE)
	cd rails1;	$(MAKE)

clean:
	cd border1;	$(MAKE) clean
	cd border2;	$(MAKE) clean
	cd border3;	$(MAKE) clean
	cd breadcrumbs;	$(MAKE) clean
	cd calendar;	$(MAKE) clean
	cd form1;	$(MAKE) clean
	cd thumbnail;	$(MAKE) clean
	cd pagelayout;	$(MAKE) clean
	cd rails1;	$(MAKE) clean
